// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function GetDownloadDir() {
  return window['go']['main']['App']['GetDownloadDir']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTasks(arg1, arg2) {
  return window['go']['main']['App']['GetTasks'](arg1, arg2);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDownloadDir(arg1) {
  return window['go']['main']['App']['SetDownloadDir'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
