// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {api} from '../models';

export function CompleteOnboarding():Promise<void>;

export function GetDownloadDir():Promise<string>;

export function GetLocalIP():Promise<Array<string>>;

export function GetStatus():Promise<main.ServiceStatus>;

export function GetTasks(arg1:number,arg2:number):Promise<api.TaskListResult>;

export function IsFirstRun():Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetDownloadDir(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
